<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv='Content-Language' content="" />
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta name="Revisit-After" content="3" />
<meta name="Robots" content="index,follow" />
<meta name="Author" content="" />

<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<title><?php echo $this->getDictio('page.title');?></title>

<!--<link rel="shortcut icon" href="<?php /*echo WEB_PATH;*/?>favicon.ico" />
<link rel="icon" href="<?php /*echo WEB_PATH;*/?>favicon.ico" />-->

<link rel="stylesheet" type="text/css" href="<?php echo WEB_ROOT;?>css/common.css" />

<!--
<link rel="stylesheet" type="text/css" href="<?php echo WEB_ROOT;?>css/data-table.css" />
<link rel="stylesheet" type="text/css" href="<?php /*echo WEB_ROOT;*/?>css/dd.css" />
<link rel="stylesheet" type="text/css" href="<?php /*echo WEB_ROOT;*/?>css/win.css" />-->
<!--link rel="stylesheet" type="text/css" href="<?php echo WEB_ROOT;?>css/win-ie.css" /-->

<?php
	$cssFiles = $this->cssFiles;
	if(count($cssFiles)>0):
		foreach ($cssFiles as $cFiles):
?>
<link rel="stylesheet" type="text/css" href="<?php echo WEB_ROOT . $cFiles;?>.css" />
<?php endforeach; endif;?>
<link rel="stylesheet" type="text/css" href="<?php echo WEB_ROOT.'skin/'.SKIN_NAME;?>/main.css" />