DROP TABLE IF EXISTS `login` ;

CREATE TABLE IF NOT EXISTS `login` (
  `LoginID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NULL,
  `UserIP` VARCHAR(45) NULL,
  `SessionID` VARCHAR(145) NULL,
  `StartTime` DATETIME NULL,
  `EndTime` DATETIME NULL,
  `DeviceID` VARCHAR(145) NULL,
  PRIMARY KEY (`LoginID`))
ENGINE = InnoDB;