DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(145) NULL,
  `Password` VARCHAR(145) NULL,
  `FirstName` VARCHAR(145) NULL,
  `LastName` VARCHAR(145) NULL,
  `DateCreated` DATETIME NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;