CREATE TABLE IF NOT EXISTS `county` (
  `CountyID` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(2) DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`CountyID`))
ENGINE = InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;