-- MySQL Script generated by MySQL Workbench
-- 01/02/15 10:44:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema budget_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `super`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `super` ;

CREATE TABLE IF NOT EXISTS `super` (
  `UserID` INT(11) NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(128) NOT NULL,
  `Password` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `family` ;

CREATE TABLE IF NOT EXISTS `family` (
  `FamilyID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(145) NULL,
  PRIMARY KEY (`FamilyID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(145) NULL,
  `Password` VARCHAR(145) NULL COMMENT '123123 as default',
  `Name` VARCHAR(245) NULL,
  `DateCreated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `FamilyID` INT NULL,
  `IsOwner` SMALLINT NULL DEFAULT 0,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `login` ;

CREATE TABLE IF NOT EXISTS `login` (
  `LoginID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NULL,
  `Lang` VARCHAR(5) NULL,
  `SessionID` VARCHAR(145) NULL,
  `StartTime` DATETIME NULL,
  `EndTime` DATETIME NULL,
  PRIMARY KEY (`LoginID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category` ;

CREATE TABLE IF NOT EXISTS `category` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(145) NULL,
  `ParentID` INT NULL,
  `FamilyID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item` ;

CREATE TABLE IF NOT EXISTS `item` (
  `ItemID` INT NOT NULL AUTO_INCREMENT,
  `CategoryID` INT NULL,
  `Price` FLOAT(10,2) NULL,
  `Desc` TEXT NULL,
  `UserID` INT NULL,
  `DateCreated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ItemID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `family`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `family` (`FamilyID`, `Name`) VALUES (1, 'Ancuta');
INSERT INTO `family` (`FamilyID`, `Name`) VALUES (2, 'Demo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `user`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `user` (`UserID`, `Email`, `Password`, `Name`, `DateCreated`, `FamilyID`, `IsOwner`) VALUES (1, 'achebv@yahoo.com', '601f1889667efaebb33b8c12572835da3f027f78', 'Florin', NULL, 1, 1);
INSERT INTO `user` (`UserID`, `Email`, `Password`, `Name`, `DateCreated`, `FamilyID`, `IsOwner`) VALUES (2, 'tutzu2u@yahoo.com', '601f1889667efaebb33b8c12572835da3f027f78', 'Andreea', NULL, 1, 0);
INSERT INTO `user` (`UserID`, `Email`, `Password`, `Name`, `DateCreated`, `FamilyID`, `IsOwner`) VALUES (3, 'demo@extjs.ro', '601f1889667efaebb33b8c12572835da3f027f78', 'demo', NULL, 2, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `category`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (1, 'cheltuieli', NULL, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (2, 'venituri', NULL, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (3, 'Masina', 1, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (4, 'Casa', 1, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (5, 'Mancare', 1, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (6, 'Facturi', 1, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (7, 'Educatie', 1, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (8, 'Sport', 1, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (9, 'Rate Banci', 1, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (10, 'Firma (I.I.)', 1, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (11, 'Personal (Membrii)', 1, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (12, 'Sanatare', 1, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (13, 'Alta Cheltuiala', 1, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (14, 'Benzina', 3, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (15, 'Consumabile', 3, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (16, 'Asigurare', 3, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (17, 'Rovigneta', 3, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (18, 'Amenda', 3, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (19, 'Consumabile', 4, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (20, 'Achizitii', 4, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (21, 'Impozite si taxe', 4, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (22, 'Mancare servici', 5, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (23, 'Mancare acasa', 5, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (24, 'Mancare oras', 5, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (25, 'Intretinere', 6, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (26, 'Avon', 6, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (27, 'Cosmote', 6, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (28, 'Gaz', 6, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (29, 'Curent', 6, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (30, 'Internet', 6, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (31, 'Orange', 6, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (32, 'Vodafone', 6, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (33, 'Gradinita', 7, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (34, 'Pregatire engleza', 7, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (35, 'Tenis', 8, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (36, 'BRD', 9, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (37, 'Transilvania', 9, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (38, 'Impozite si taxe', 10, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (39, 'Contributie pensie privata', 10, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (40, 'Florin', 11, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (41, 'Andreea', 11, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (42, 'Cosmin', 11, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (43, 'Medicamente', 12, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (44, 'Orice alta cheltuiala', 13, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (45, 'Acordare imprumut', 13, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (46, 'Salarii', 2, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (47, 'Alocatii', 2, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (48, 'Indemnizatii/Somaj', 2, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (49, 'Proiecte Extra', 2, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (50, 'Vanzare de bunuri', 2, NULL);
INSERT INTO `category` (`CategoryID`, `Name`, `ParentID`, `FamilyID`) VALUES (51, 'Recuperare imprumut', 2, NULL);

COMMIT;

